export const colors = {
    ink: '#14171F',
    paper: '#F1F3f7',
    card: '#FFFFFF',
    border: '#E3E6EC',
    muted: '#6B7280',
    signal: '#3556FF',
    signalDim: '#EAEEFF',
    amber: '#F5A623',
    amberDim: '#FFF3DF',
    success: '#1F9D64',
    successDim: '#E7F6EE',
    danger: '#E5484D',
    dangerDim: '#FDEAEA',
    purple: '#7C5CFF',
    purpleDim: '#EFEAFF',
    pink: '#E8489A',
    pinkDim: '#FCE8F2',
}